### ISSUE TITLE
An issue about the function flearn.utils.model_utils.project

### ISSUE THREAD

**Issue by WwZzz** [litian96/fair_flearn#10]
Dear author, sorry for bothering you again.
When I use optimizer 'afl', I notice the function 'flearn.utils.model_utils.project' sometimes returns a result not in the probability simplex. 
![image](https://user-images.githubusercontent.com/20792079/98665176-45e29880-2386-11eb-96dd-1e2610e25380.png)
![image](https://user-images.githubusercontent.com/20792079/98665187-4bd87980-2386-11eb-92c8-3416eb763e07.png)
Then I read the article "Projection onto the probability simplex: An efficient algorithm with a simple proof, and an application" and compare the algorithm with your code.  I think 'np.asarray(u)[:i]' should be replaced by 'np.asarray(u)[:i+1]' in the red line.  
![image](https://user-images.githubusercontent.com/20792079/98665528-c3a6a400-2386-11eb-8a50-cdbc1d95fb76.png)
![image](https://user-images.githubusercontent.com/20792079/98665480-b1c50100-2386-11eb-869e-dd62f0b7701f.png)
And after this change, it projects a result in the probability simplex. 
![image](https://user-images.githubusercontent.com/20792079/98666873-96f38c00-2388-11eb-87f8-8816775113cf.png)
![image](https://user-images.githubusercontent.com/20792079/98666570-2ba9ba00-2388-11eb-8679-d57b999a2765.png)

**Comment by litian96** [comment]
Thanks for catching it! Yes, you are correct---this is an error when we were cleaning up the code for the release.
