### ISSUE TITLE
Where the .mat file?

### ISSUE THREAD

**Issue by SAGIN-Xu** [litian96/fair_flearn#2]

**Comment by litian96** [comment]
As described in the [README](https://github.com/litian96/fair_flearn/tree/master/data/vehicle) of the Vehicle dataset, vehicle.mat can be downloaded at: https://drive.google.com/file/d/1x39M3wYLt0VKNS8RSiwohT-VfVoGeKlM/view.

Please let me know if you have problems accessing the dataset.
