### ISSUE TITLE
Got "TypeError: select_clients() got multiple values for argument 'num_clients'" error when run q-MAML

### ISSUE THREAD

**Issue by ddayzzz** [litian96/fair_flearn#4]
I got "TypeError: select_clients() got multiple values for argument 'num_clients'" error when run q-MAML.  I found that `select_clients` in [maml.py](https://github.com/litian96/fair_flearn/blob/610b458312559a5ce70203f23efeb0ab9963e765/flearn/trainers/maml.py#L34) passes four arguments: 
```python
self.select_clients(i, pk, self.held_out, num_clients=self.clients_per_round)
```
However, the base method accepts only 3 arguments: [fedbase.py](https://github.com/litian96/fair_flearn/blob/610b458312559a5ce70203f23efeb0ab9963e765/flearn/trainers/fedbase.py#L116):
```python
def select_clients(self, round, pk, num_clients=20):
   ...
```

**Comment by litian96** [comment]
Thanks for letting me know. Have fixed---see commits [here](https://github.com/litian96/fair_flearn/commit/5a5e461f2110bcefa2313f9362a3b2c59efceaf3).

**Comment by ddayzzz** [comment]
Thank you. I ran the fixed version, but I got another problem after finishing the meta-train. 

```
###### finish meta-training, start meta-testing ######
Traceback (most recent call last):
  File "/home/wzw/codes/fair_flearn/main.py", line 166, in <module>
    main()
  File "/home/wzw/codes/fair_flearn/main.py", line 163, in main
    t.train()
  File "/home/wzw/codes/fair_flearn/flearn/trainers/maml.py", line 68, in train
    ct, cl, ns = c.test_error_and_loss()
AttributeError: 'Client' object has no attribute 'test_error_and_loss'
```

It seems that `test_error_and_loss` isn't defined since initial version.

**Comment by litian96** [comment]
there are slight mismatches between the code for meta-learning and the previous code for federated learning due to copy-paste errors. Just fixed.

**Comment by ddayzzz** [comment]
Thank you.
