### ISSUE TITLE
q-FedSGD update

### ISSUE THREAD

**Issue by vcpudding** [litian96/fair_flearn#5]
Dear author, thanks for sharing your wonderful codes.

In the ICLR paper Algorithm 1, the server updates w by (sum of deltas) / (sum of hs). As I understand from the paper, the h_k^t's are the upper bounds of the gradient on each device. So why is the summation not taken over the (delta_k^t / h_k^t)? What is the rationale in aggregating all the upper bounds and use the sum as a denominator?

**Comment by litian96** [comment]
The numerator can be considered as the mini-batch gradient of the objective, and the denominator is the estimated Lipschitz constant of the gradient on the numerator, which is 1 / the estimated step size.

**Comment by litian96** [comment]
please let me know if this does not answer your question

**Comment by vcpudding** [comment]
Thanks for your reply. I think I get what you mean, I'm just wondering if
there would be a better bound on the step size than the sum of (potentially
loose) bounds :D. Please let me know if you have any further thoughts on
this :)

**Comment by litian96** [comment]
that's a good point. We use the heuristic of estimating the step size as the inverse of the estimated Lipschitz constant. How to estimate the Lipschitz constant itself is an open problem (we use the heuristic based on Lemma 3). The estimate might not be very accurate, but we empirically demonstrate that we achieve similar (or better) performance than distributed SGD with a best-tuned fixed step size on all the datasets (see Figure 4 in https://openreview.net/pdf?id=ByexElSYDr).
