### ISSUE TITLE
Theoretical analysis of q-FFL

### ISSUE THREAD

**Issue by Abida16** [litian96/fair_flearn#6]
Dear author
I have a question on the theoretical analysis of q-FFL that I may not be understanding due to a lack of my knowledge. In first equation in the proof of lemma 7, can you explain the inequality? I mean how does this hold if I cancel out the identical terms from both sides. We may look into the attachment for the clarification of my question.  
![Screen Shot 2020-07-10 at 4 11 36 PM](https://user-images.githubusercontent.com/18519982/87204555-c0ad8100-c2ca-11ea-988b-7578989c7ad8.png)

Also the same question for lemma 8. How does inequality hold in the marked section of the image? To me it seems like it contradicts the inequality condition of lemma 7.
![Screen Shot 2020-07-10 at 4 11 55 PM](https://user-images.githubusercontent.com/18519982/87204681-066a4980-c2cb-11ea-806c-70c516df673e.png)

**Comment by litian96** [comment]
` \sum F_k^2 (w_1^*) <= \sum F_k^2 (w_0^*)` holds because f_1(w_1^\*) \leq f_1(w_0^\*) (w_1* is the minimizer of f_1(w)). (f_q(w) is defined right after Eq (8).)
` \sum F_k (w_1^*) >= \sum F_k (w_0^*) ` holds because f_0(w_1^\*) \geq f_0(w_0^\*).

**Comment by beirami** [comment]
Note that as Tian mentioned, by definition, w_0^* is the minimizer of \sum_{k} F_k(w) and w_1^* is the minimizer of \sum_{k} (F_k(w))^2. Hence, 
1) for any w, \sum_{k} F_k(w) >=  \sum_{k} F_k(w_0^* ), and in particular, \sum_{k} F_k(w_1^* ) >=  \sum_{k} F_k(w_0^*).
2) for any w, \sum_{k} (F_k(w))^2 >=  \sum_{k} (F_k(w_1^* ))^2, and in particular, \sum_{k} (F_k(w_0^* ))^2 >=  \sum_{k} (F_k(w_1^*))^2.

**Comment by Abida16** [comment]
Thanks. Got it.
